language: node_js
node_js:
  - 'node'
cache:
  directories:
    - 'node_modules'
script: npm test # Here you could also run a build step
before_deploy: npm install now --no-save
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
